### ISSUE TITLE
Recently, most people tend to regard GS as the 3D representation. I'm not quite sure, even doubtful, that it's the best approach. It's preferable to have representations akin to multi-plane, continuous, and efficient representation.

### ISSUE THREAD

**Issue by yuedajiong** [WU-CVGL/MVControl-threestudio#5]

**Comment by lizhiqi49** [comment]
3DGS draws people's attention due to its nice properties brought by its absolutely explicit format. Continuity means Implicit representations, which can propose better visual and geometry quality, at this stage, but suffer from long optimization time. Both kinds of representation have their pros and cons.

**Comment by yuedajiong** [comment]
对于“偏重构”来说，连续性优化比较慢，哪怕是multiplane和hash-based都还是差不少；对于GS points，有效性除了半显式的表示，速度来源于：基于梯度的优化，特别是还有点的移除和增加；对于mesh，flexicubes，其实速度来源也类似，直接基于梯度，而且也有移除和增加。   

对于“偏生成”来说，本质都是在网络的中后部分，也就是generation主干的后面，要么产生GS points，要么产生一个MLP为主的隐式表示。 这个其实infer过程，“速度其实没有本质差别”，都是一把梭推理过来one-shot-infer。 对于GS来说，要让“oneshot gen”出来的那一堆高斯点，具有很好的性质，其实比较难。这些性质包含（我用“杜绝”和“尽量”来描述）：杜绝：深度完全不对的那种漂浮点, ...；尽量：尽量表面对齐，尽量不要太大的高斯点，尽量交错少，...
